### ISSUE TITLE
ALARA compilation problem

### ISSUE THREAD

**Issue by kyfranzen** [svalinn/ALARA#30] opened 2019-10-09 22:11 UTC
Hi,
When trying to install ALARA following the README instructions I get the following error after the make command:
ake[3]: Leaving directory `/localhome/restricted/ken/alara/bld/src/Util'
make[3]: Entering directory `/localhome/restricted/ken/alara/bld/src'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/localhome/restricted/ken/alara/bld/src'
make[2]: Leaving directory `/localhome/restricted/ken/alara/bld/src'
Making all in tools
make[2]: Entering directory `/localhome/restricted/ken/alara/bld/tools'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/localhome/restricted/ken/alara/bld/tools'
Making all in doc
make[2]: Entering directory `/localhome/restricted/ken/alara/bld/doc'
make[2]: *** No rule to make target `commandtext.html', needed by `all-am'.  Stop.
make[2]: Leaving directory `/localhome/restricted/ken/alara/bld/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/localhome/restricted/ken/alara/bld'
make: *** [all] Error 2
(py27) [ken@attila bld]$

Any ideas on what to do?

Thanks!,
Ken Franzen

**Comment by ljacobson64** [comment] 2019-10-11 14:45
I get the same error. It appears to have been caused by #22.  I'm not entirely sure how to fix it at this time

**Comment by gonuke** [comment] 2019-10-13 21:42
Thanks for reporting this!  We've been updating the way that we do documentation, but didn't consider how it was integrated with the build system.  I've pushed a fix in #31

**Comment by ljacobson64** [comment] 2019-10-15 00:24
@kyfranzen can you try again? @gonuke fixed this issue in #31.

**Comment by kyfranzen** [comment] 2019-10-15 16:01
I successfully tried to install the latest master branch.
Nicely done!
Thanks,
Ken

**Closed** 2019-10-15 18:51 UTC
